# Generated by Django 4.2.19 on 2025-07-26 14:45

from django.db import migrations


def cleanup_duplicate_reminders(apps, schema_editor):
    """Remove duplicate reminders, keeping the most recent one for each (member, type, due_date) combination"""
    Reminder = apps.get_model("visits", "Reminder")

    # Get all unique combinations of member, reminder_type, due_date
    unique_combinations = Reminder.objects.values(
        "member", "reminder_type", "due_date"
    ).distinct()

    for combo in unique_combinations:
        # Get all reminders for this combination
        reminders = Reminder.objects.filter(
            member=combo["member"],
            reminder_type=combo["reminder_type"],
            due_date=combo["due_date"],
        ).order_by(
            "-created_date"
        )  # Most recent first

        # If there are duplicates, delete all except the most recent
        if reminders.count() > 1:
            reminders_to_delete = reminders[1:]  # All except the first (most recent)
            for reminder in reminders_to_delete:
                reminder.delete()


def reverse_cleanup(apps, schema_editor):
    """This operation cannot be reversed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_reminder"),
    ]

    operations = [
        # First clean up duplicates
        migrations.RunPython(cleanup_duplicate_reminders, reverse_cleanup),
        # Then apply the new constraint
        migrations.AlterUniqueTogether(
            name="reminder",
            unique_together={("member", "reminder_type", "due_date")},
        ),
    ]
