# Generated by Django 4.2.19 on 2025-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20250726_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together=set(),
        ),
    ]
