# Generated by Django 4.2.19 on 2025-07-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0006_alter_reminder_unique_together"),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Reminder",
                ),
            ],
            database_operations=[],
        )
    ]
