# Generated by Django 4.2.19 on 2025-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20250726_2232'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['member', 'check_in_time'], name='visit_member_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['check_in_time'], name='visit_checkin_idx'),
        ),
    ]
