# Generated by Django 4.2.19 on 2025-02-22 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment', name='membership_start_date', ), migrations.AddField(
            model_name='payment', name='duration_months', field=models.IntegerField(
                choices=[
                    (1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=1), ), migrations.AddField(
                        model_name='payment', name='notes', field=models.TextField(
                            blank=True), ), migrations.AlterField(
                                model_name='payment', name='payment_date', field=models.DateTimeField(
                                    default=django.utils.timezone.now), ), ]
