# Generated by Django 4.2.19 on 2025-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_membership_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='payment',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
