# Generated by Django 4.2.19 on 2025-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_duration_choice_alter_payment_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='membership_end_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
