# Generated by Django 4.2.19 on 2025-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_membership_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TRANSFER', 'Transfer'), ('QRIS', 'QRIS'), ('CASH', 'Cash')], default='TRANSFER', max_length=10),
        ),
    ]
