# Generated by Django 4.2.19 on 2025-06-01 16:21

from django.db import migrations


def populate_packages_data(apps, schema_editor):
    Package = apps.get_model("payments", "Package")
    db_alias = schema_editor.connection.alias

    packages_data = [
        {"code": "REG0", "default_price": 75000, "description": "Gym Reguler 1x visit"},
        {"code": "REG1", "default_price": 400000, "description": "Gym Reguler 1 bulan"},
        {
            "code": "REG3",
            "default_price": 1000000,
            "description": "Gym Reguler 3 bulan",
        },
        {
            "code": "REG6",
            "default_price": 1500000,
            "description": "Gym Reguler 6 bulan",
        },
        {
            "code": "REG12",
            "default_price": 2500000,
            "description": "Gym Reguler 12 bulan",
        },
        {
            "code": "KELASAVISIT",
            "default_price": 100000,
            "description": "Kelas A 1x Visit",
        },
        {
            "code": "KELASAWEEK",
            "default_price": 260000,
            "description": "Kelas A Mingguan",
        },
        {"code": "KELASA1", "default_price": 300000, "description": "Kelas A 1 Bulan"},
        {"code": "KELASA3", "default_price": 750000, "description": "Kelas A 3 Bulan"},
        {"code": "KELASA6", "default_price": 1200000, "description": "Kelas A 6 Bulan"},
        {
            "code": "KELASBUNDA1",
            "default_price": 700000,
            "description": "Kelas Bunda A 1 Bulan",
        },
        {
            "code": "KELASBUNDA3",
            "default_price": 1750000,
            "description": "Kelas Bunda A 3 Bulan",
        },
        {
            "code": "KELASBUNDA6",
            "default_price": 2700000,
            "description": "Kelas Bunda A 6 Bulan",
        },
        {
            "code": "KELASBVISIT",
            "default_price": 150000,
            "description": "Kelas B 1x Visit",
        },
        {"code": "KELASB1", "default_price": 650000, "description": "Kelas B 1 Bulan"},
        {"code": "KELASB3", "default_price": 1500000, "description": "Kelas B 3 Bulan"},
        {"code": "KELASB6", "default_price": 2880000, "description": "Kelas B 6 Bulan"},
        {
            "code": "KELASBUNDB1",
            "default_price": 1050000,
            "description": "Kelas Bunda B 1 Bulan",
        },
        {
            "code": "KELASBUNDB3",
            "default_price": 2500000,
            "description": "Kelas Bunda B 3 Bulan",
        },
        {
            "code": "KELASBUNDB6",
            "default_price": 4380000,
            "description": "Kelas Bunda B 6 Bulan",
        },
        {"code": "PTREG1", "default_price": 275000, "description": "PT Reguler 1 Sesi"},
        {
            "code": "PTREG4",
            "default_price": 1000000,
            "description": "PT Reguler 4 Sesi",
        },
        {
            "code": "PTREG10",
            "default_price": 2350000,
            "description": "PT Reguler 10 Sesi",
        },
        {
            "code": "PTREG16",
            "default_price": 3520000,
            "description": "PT Reguler 16 Sesi",
        },
        {
            "code": "PTREG24",
            "default_price": 4800000,
            "description": "PT Reguler 24 Sesi",
        },
        {
            "code": "PTREG50",
            "default_price": 9000000,
            "description": "PT Reguler 50 Sesi",
        },
        {
            "code": "PTREG100",
            "default_price": 17500000,
            "description": "PT Reguler 100 Sesi",
        },
        {
            "code": "PTBUND4",
            "default_price": 1300000,
            "description": "PT Bundling 4 Sesi",
        },
        {
            "code": "PTBUND10",
            "default_price": 2970000,
            "description": "PT Bundling 10 Sesi",
        },
        {
            "code": "PTBUND16",
            "default_price": 4300000,
            "description": "PT Bundling 16 Sesi",
        },
        {
            "code": "PTBUND24",
            "default_price": 5800000,
            "description": "PT Bundling 24 Sesi",
        },
        {
            "code": "PTBUND100",
            "default_price": 19420000,
            "description": "PT Bundling 100 Sesi",
        },
    ]

    for package_data in packages_data:
        Package.objects.using(db_alias).create(
            code=package_data["code"],
            default_price=package_data["default_price"],
            description=package_data["description"],
        )


def revert_populate_packages_data(apps, schema_editor):
    Package = apps.get_model("payments", "Package")
    db_alias = schema_editor.connection.alias
    Package.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_package"),
    ]

    operations = [
        migrations.RunPython(populate_packages_data, revert_populate_packages_data),
    ]
