# Generated by Django 4.2.19 on 2025-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='apakah_nyicil',
            field=models.BooleanField(default=False, help_text='Apakah pembayaran ini dicicil?'),
        ),
    ]
