# Generated by Django 4.2.19 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_apakah_nyicil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='apakah_nyicil',
            field=models.BooleanField(default=False, help_text='Apakah cicilan?'),
        ),
    ]
