# Generated by Django 4.2.19 on 2025-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_apakah_nyicil'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='skip_membership_update',
            field=models.BooleanField(default=False, help_text='Skip automatic membership update (manual update required)'),
        ),
    ]
