# Generated by Django 4.2.19 on 2025-08-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_skip_membership_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='duration_choice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='duration_days',
        ),
    ]
