# Generated by Django 4.2.19 on 2025-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_duration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(help_text='Code format: TYPE-LEVEL-DURATION. A DURATION of "0" signifies a single-visit pass.', max_length=30, unique=True),
        ),
    ]
