# Generated by Django 4.2.19 on 2025-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrandOpeningRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('phone_number', models.CharField(max_length=20, verbose_name='No. HP')),
                ('age', models.IntegerField(verbose_name='Usia')),
                ('gym_experience', models.CharField(max_length=100, verbose_name='Udah pernah rutin nge-Gym atau belum?')),
                ('know_mulai_gym_from', models.CharField(max_length=255, verbose_name='Kenal Mulai Gym dari mana?')),
                ('social_media_username', models.CharField(blank=True, max_length=100, verbose_name='Username akun Instagram/TikTok/Facebook (Opsional)')),
                ('visit_date', models.CharField(choices=[('19 Juli 2025', 'Sabtu, 19 Juli 2025'), ('20 Juli 2025', 'Minggu, 20 Juli 2025')], max_length=20, verbose_name='Mau datang kapan?')),
                ('time_slot', models.CharField(choices=[('Pagi', 'Pagi (08:00 - 12:00)'), ('Siang', 'Siang (12:00 - 16:00)'), ('Sore', 'Sore (16:00 - 20:00)'), ('Malam', 'Malam (20:00 - 22:00)')], max_length=10, verbose_name='Pilih waktu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grand Opening Registration',
                'verbose_name_plural': 'Grand Opening Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
