# Generated by Django 4.2.19 on 2025-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_opening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandopeningregistration',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='grandopeningregistration',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='grandopeningregistration',
            name='visit_schedule',
            field=models.CharField(default='', max_length=100, verbose_name='Mau datang kapan (19 atau 20, pagi/siang/sore/malam)?'),
        ),
    ]
