# Generated by Django 4.2.19 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_opening', '0002_remove_grandopeningregistration_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandopeningregistration',
            name='visit_schedule',
            field=models.CharField(default='', max_length=100, verbose_name='Mau datang kapan? (mulai dari 19 Juli 10.00 pagi ya!)'),
        ),
    ]
