# Generated by Django 4.2.19 on 2025-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classinstance',
            index=models.Index(fields=['date', 'start_time'], name='class_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='classinstance',
            index=models.Index(fields=['status'], name='class_status_idx'),
        ),
    ]
