# Generated by Django 4.2.19 on 2026-08-02 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_member_booking_blocked_until'),
        ('classes', '0002_classinstance_class_date_time_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Matikan ini untuk menghentikan semua penalti tanpa mengubah data.')),
                ('window_days', models.PositiveSmallIntegerField(default=15, help_text='Berapa hari ke belakang yang dihitung.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('misses_allowed', models.PositiveSmallIntegerField(default=2, help_text='Berapa kali boleh nggak dateng dalam periode itu sebelum kena penalti. 2 berarti penalti mulai dari kali ke-3.', validators=[django.core.validators.MaxValueValidator(50)])),
                ('ban_days', models.PositiveSmallIntegerField(default=3, help_text='Berapa hari booking kelas dikunci tiap kali kena penalti.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('effective_from', models.DateField(help_text='Kelas sebelum tanggal ini tidak dihitung. Diisi tanggal fitur ini mulai jalan, biar nggak ada yang kena penalti karena kebiasaan lama.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Penalti Kelas',
                'verbose_name_plural': 'Pengaturan Penalti Kelas',
            },
        ),
        migrations.CreateModel(
            name='BookingPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('blocked_until', models.DateField(help_text='Hari pertama member bisa booking lagi (tanggal ini sudah boleh).')),
                ('miss_days', models.PositiveSmallIntegerField(help_text='Berapa hari bolos dalam periode saat penalti ini dibuat.')),
                ('bookings_cancelled', models.PositiveSmallIntegerField(default=0)),
                ('waitlists_cleared', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_penalties', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Penalti Kelas',
                'verbose_name_plural': 'Penalti Kelas',
                'ordering': ['-starts_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misses', to='classes.classinstance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_misses', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Kelas Bolos',
                'verbose_name_plural': 'Kelas Bolos',
                'ordering': ['-class_date', '-class_start_time'],
                'indexes': [models.Index(fields=['member', 'class_date'], name='classes_cla_member__2af62a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='classmiss',
            constraint=models.UniqueConstraint(fields=('member', 'class_instance'), name='one_miss_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingpenalty',
            constraint=models.UniqueConstraint(fields=('member', 'starts_on'), name='one_penalty_per_member_per_day'),
        ),
    ]
