# Generated by Django 4.2.19 on 2026-09-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_member_booking_blocked_until'),
        ('classes', '0006_gymclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kurang'), (2, 'Oke'), (3, 'Mantap')], help_text='Kosong kalau member cuma melewati pertanyaannya.', null=True, verbose_name='Penilaian')),
                ('attended', models.BooleanField(default=True, help_text='Dicentang kecuali member bilang nggak jadi ikut kelasnya.', verbose_name='Jadi datang')),
                ('intensity', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enteng'), (2, 'Pas'), (3, 'Berat')], null=True, verbose_name='Beratnya')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Kode-kode dari classes/reviews.py, bentuknya ["seru", "pelatih"].', verbose_name='Pilihan cepat')),
                ('comment', models.TextField(blank=True, verbose_name='Catatan')),
                ('skipped', models.BooleanField(default=False, help_text='Member menutup pertanyaannya tanpa menjawab.', verbose_name='Dilewati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classes.classinstance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Penilaian Kelas',
                'verbose_name_plural': 'Penilaian Kelas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='review_rating_idx'), models.Index(fields=['created_at'], name='review_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='classreview',
            constraint=models.UniqueConstraint(fields=('member', 'class_instance'), name='one_review_per_booking'),
        ),
    ]
