# Generated by Django 4.2.19 on 2025-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='detailed_muscle_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
