# Generated by Django 4.2.19 on 2025-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_detailed_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='anonymous_views',
            field=models.PositiveIntegerField(default=0, help_text='Views from anonymous users'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='authenticated_views',
            field=models.PositiveIntegerField(default=0, help_text='Views from logged-in users'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of page views'),
        ),
    ]
