# Generated by Django 4.2.19 on 2025-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_anonymous_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='additional_videos',
            field=models.JSONField(blank=True, default=list, help_text='Additional video URLs for tips and detailed explanations'),
        ),
    ]
