# Generated by Django 4.2.19 on 2025-07-26 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0015_member_social_media_username_and_more"),
        ("visits", "0006_alter_reminder_unique_together"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Reminder",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "reminder_type",
                            models.CharField(
                                choices=[
                                    ("PAYMENT_DUE", "Payment Due (Cicilan)"),
                                    ("NO_VISIT", "No Visit (2 Weeks)"),
                                    ("MEMBERSHIP_EXPIRING", "Membership Expiring"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("reason", models.TextField()),
                        (
                            "due_date",
                            models.DateField(help_text="The date this reminder is for"),
                        ),
                        (
                            "created_date",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        ("is_resolved", models.BooleanField(default=False)),
                        ("resolved_date", models.DateTimeField(blank=True, null=True)),
                        (
                            "member",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.member",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "visits_reminder",
                        "ordering": ["-created_date"],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
