# Generated by Django 4.2.19 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('PAYMENT_DUE', 'Bayar Cicilan'), ('NO_VISIT', 'Lama Tidak Visit'), ('MEMBERSHIP_EXPIRING', 'Membership Berakhir')], max_length=20),
        ),
    ]
