# Generated by Django 4.2.19 on 2025-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('PAYMENT_DUE', 'Bayar Cicilan'), ('NO_VISIT', 'Lama Tidak Visit'), ('MEMBERSHIP_EXPIRING', 'Membership Berakhir'), ('LOKER', 'Loker'), ('LAINNYA', 'Lainnya')], max_length=20),
        ),
    ]
