# Generated by Django 4.2.19 on 2026-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('PAYMENT_DUE', 'Bayar Cicilan'), ('NO_VISIT', 'Lama Tidak Visit'), ('MEMBERSHIP_EXPIRING', 'Membership Berakhir'), ('PENALTI_KELAS', 'Penalti Kelas'), ('KELAS_LIBUR', 'Kelas Ditiadakan'), ('LOKER', 'Loker'), ('LAINNYA', 'Lainnya')], max_length=20),
        ),
    ]
