# Generated by Django 4.2.19 on 2025-07-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer')], default='CASH', max_length=10),
        ),
    ]
