# Generated by Django 4.2.19 on 2025-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
