# Generated by Django 4.2.19 on 2025-07-02 03:03

from django.db import migrations

PRODUCTS = {
    "Aqua 600ml": 5000,
    "Gelas kertas": 2000,
    "Pocari Sweat": 12000,
    "Kopi Excelso Sachet": 4000,
    "L-Men Protein Cappucino": 16000,
    "L-Men Protein Coklat": 16000,
    "Kopi Kenangan Indonesiano (Black)": 12000,
    "Nescafe Ice Black": 12000,
    "Teh Botol Less Sugar 250ml": 7000,
}


def populate_products(apps, schema_editor):
    Product = apps.get_model("purchases", "Product")
    for name, price in PRODUCTS.items():
        Product.objects.get_or_create(name=name, defaults={"price": price})


def remove_products(apps, schema_editor):
    Product = apps.get_model("purchases", "Product")
    Product.objects.filter(name__in=PRODUCTS.keys()).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_alter_sale_payment_method"),
    ]

    operations = [
        migrations.RunPython(populate_products, remove_products),
    ]
