# Generated by Django 4.2.19 on 2025-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_populate_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer'), ('DITRAKTIR_ONEL', 'Ditraktir Onel')], max_length=20),
        ),
    ]
