# Generated by Django 4.2.19 on 2025-02-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active_until',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
    ]
