# Generated by Django 4.2.19 on 2025-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_member_active_until_remove_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
