# Generated by Django 4.2.19 on 2025-03-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_password_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_member',
        ),
    ]
