# Generated by Django 4.2.19 on 2025-04-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_member_is_active_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
