# Generated by Django 4.2.19 on 2025-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', 'Perempuan'), ('M', 'Laki-laki')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='years_of_working_out',
            field=models.CharField(max_length=100),
        ),
    ]
