# Generated by Django 4.2.19 on 2025-04-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_member_address_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='why_choose_mulai',
            field=models.TextField(blank=True, default=''),
        ),
    ]
