# Generated by Django 4.2.19 on 2025-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_member_why_choose_mulai'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pemula_active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pt_session_count',
            field=models.IntegerField(default=0, help_text='Jumlah sesi personal training yang tersisa'),
        ),
        migrations.AddField(
            model_name='member',
            name='semi_private_active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
