# Generated by Django 4.2.19 on 2025-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_member_pemula_active_until_member_pt_session_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('phone_number', models.CharField(max_length=20, verbose_name='No. HP')),
                ('has_worked_out_before', models.BooleanField(verbose_name='Udah pernah rutin nge-Gym atau belum?')),
                ('social_media_username', models.CharField(blank=True, max_length=100, verbose_name='Username akun Instagram/TikTok/Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tamu',
                'verbose_name_plural': 'Tamu',
                'ordering': ['-created_at'],
            },
        ),
    ]
