# Generated by Django 4.2.19 on 2025-06-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_tamu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='has_worked_out_before',
            field=models.CharField(max_length=100, verbose_name='Udah pernah rutin nge-Gym atau belum?'),
        ),
    ]
