# Generated by Django 4.2.19 on 2025-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tamu_has_worked_out_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masukkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nama')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Kontak (no WA / sosial media)')),
                ('feedback', models.TextField(verbose_name='Masukkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Masukkan',
                'verbose_name_plural': 'Masukkan',
                'ordering': ['-created_at'],
            },
        ),
    ]
