# Generated by Django 4.2.19 on 2025-07-19 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_masukkan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='No. HP')),
                ('gym_experience', models.CharField(blank=True, max_length=100, verbose_name='Udah pernah rutin nge-Gym atau belum?')),
                ('social_media_username', models.CharField(blank=True, max_length=100, verbose_name='Username akun Instagram/TikTok/Facebook')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Prospek oleh')),
            ],
            options={
                'verbose_name': 'Prospek',
                'verbose_name_plural': 'Prospek',
                'ordering': ['-created_at'],
            },
        ),
    ]
