# Generated by Django 4.2.19 on 2025-07-26 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='social_media_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='(Opsional) Akun Instagram/TikTok'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Disubmit oleh'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='gym_experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Opsional) Udah pernah rutin nge-Gym atau belum?'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='social_media_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Opsional) Username ig/fb/tiktok'),
        ),
    ]
