# Generated by Django 4.2.19 on 2025-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_member_social_media_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_pemula',
            field=models.BooleanField(blank=True, help_text='Status pemula member - bisa true, false, atau null', null=True),
        ),
    ]
