# Generated by Django 4.2.19 on 2025-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_member_is_pemula'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='is_pemula',
            field=models.BooleanField(blank=True, help_text='Status pemula tamu - bisa true, false, atau null', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_pemula',
            field=models.BooleanField(blank=True, help_text='Status pemula member - bisa true, false, atau kosong', null=True),
        ),
    ]
