# Generated by Django 4.2.19 on 2025-09-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tamu_is_pemula_alter_member_is_pemula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='has_worked_out_before',
            field=models.CharField(max_length=100, verbose_name='Sudah pernah rutin nge-Gym? Kalau sudah, berapa lama?'),
        ),
    ]
