# Generated by Django 4.2.19 on 2025-12-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_tamu_has_worked_out_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='asked_google_review',
            field=models.BooleanField(default=False, help_text='Flag: sudah diminta untuk memberikan Google review'),
        ),
        migrations.AddField(
            model_name='member',
            name='asked_referral',
            field=models.BooleanField(default=False, help_text='Flag: sudah ditanya apakah punya kenalan yang bisa diajak ke gym'),
        ),
        migrations.AddField(
            model_name='member',
            name='missed_installment',
            field=models.BooleanField(default=False, help_text='Flag: member yang cicilan tapi tidak melanjutkan pembayaran'),
        ),
    ]
