# Generated by Django 4.2.19 on 2026-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_member_tracking_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Catatan internal admin saja, tidak ditampilkan ke member'),
        ),
    ]
