# Generated by Django 4.2.19 on 2026-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_member_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMember',
            fields=[
            ],
            options={
                'verbose_name': 'Active Member',
                'verbose_name_plural': 'Active Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='skip_auto_reminder',
            field=models.BooleanField(default=False, help_text='Flag: jangan buat reminder otomatis untuk member ini'),
        ),
    ]
