# Generated by Django 4.2.19 on 2026-08-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_skip_auto_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='booking_blocked_until',
            field=models.DateField(blank=True, help_text='Booking kelas dikunci sampai tanggal ini (tanggal ini sudah boleh booking lagi). Kosongkan untuk membuka kunci sekarang.', null=True),
        ),
    ]
