# Generated by Django 4.2.19 on 2026-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_member_booking_blocked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='masukkan',
            name='topic',
            field=models.CharField(blank=True, choices=[('ALAT', 'Alat'), ('KEBERSIHAN', 'Kebersihan'), ('KELAS', 'Kelas'), ('PELAYANAN', 'Pelayanan'), ('JADWAL', 'Jadwal'), ('LAINNYA', 'Lainnya')], default='', max_length=12, verbose_name='Topik'),
        ),
    ]
