# Generated by Django 4.2.19 on 2026-08-01 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='Misal 5.0', max_digits=2, verbose_name='Rating Google')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Jumlah ulasan di Google Maps.', verbose_name='Jumlah ulasan')),
                ('maps_url', models.URLField(help_text='Link ke listing Google Maps Mulai Gym.', max_length=300, verbose_name='Link Google Maps')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir diperbarui')),
            ],
            options={
                'verbose_name': 'Ringkasan Ulasan Google',
                'verbose_name_plural': 'Ringkasan Ulasan Google',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Nama seperti yang tertulis di ulasan. Boleh nama depan saja.', max_length=80, verbose_name='Nama')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('text', models.TextField(help_text='Tulis apa adanya, jangan diedit-edit.', verbose_name='Ulasan')),
                ('review_url', models.URLField(blank=True, help_text='Opsional. Link ke ulasan aslinya di Google Maps.', max_length=300, verbose_name='Link ulasan')),
                ('is_active', models.BooleanField(default=True, help_text='Hilangkan centang untuk menyembunyikan tanpa menghapus.', verbose_name='Tayang')),
                ('priority', models.IntegerField(default=0, help_text='Makin besar, makin depan.', verbose_name='Prioritas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ulasan Member',
                'verbose_name_plural': 'Ulasan Member',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
