# Generated by Django 4.2.19 on 2026-08-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_add_skip_auto_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_slug', models.CharField(max_length=50)),
                ('question_key', models.CharField(max_length=50)),
                ('chosen', models.CharField(blank=True, max_length=8)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_answers', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Jawaban Kuis',
                'verbose_name_plural': 'Jawaban Kuis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question_key'], name='nutrition_q_questio_f29aea_idx'), models.Index(fields=['member', 'question_key'], name='nutrition_q_member__dc3145_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_slug', models.CharField(max_length=50)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('best_correct', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_finished_at', models.DateTimeField(auto_now_add=True)),
                ('last_finished_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_progress', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Progres Bab',
                'verbose_name_plural': 'Progres Bab',
                'ordering': ['-last_finished_at'],
                'indexes': [models.Index(fields=['chapter_slug'], name='nutrition_c_chapter_7c1e9d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.UniqueConstraint(fields=('member', 'chapter_slug'), name='one_progress_per_chapter'),
        ),
    ]
