# Generated by Django 4.2.19 on 2026-08-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_member_booking_blocked_until'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode tetap, dipakai buat nyocokin jawaban yang udah tercatat. Jangan diubah.', max_length=20, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Urutan dalam rotasi. Kosongkan (0) buat ditaruh paling akhir.')),
                ('question', models.TextField()),
                ('choices', models.JSONField(help_text='Bentuknya [{"key": "a", "text": "..."}, ...]')),
                ('answer', models.CharField(help_text='Key jawaban yang benar, misal b', max_length=8)),
                ('explanation', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Matikan buat ngeluarin soal ini dari rotasi tanpa menghapusnya.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soal Harian',
                'verbose_name_plural': 'Soal Harian',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='nutrition_d_is_acti_c31c8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateField()),
                ('chosen', models.CharField(blank=True, max_length=8)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_answers', to='accounts.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='nutrition.dailyquestion')),
            ],
            options={
                'verbose_name': 'Jawaban Harian',
                'verbose_name_plural': 'Jawaban Harian',
                'ordering': ['-answer_date'],
                'indexes': [models.Index(fields=['member', 'answer_date'], name='nutrition_d_member__e512ce_idx'), models.Index(fields=['question'], name='nutrition_d_questio_06d151_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyanswer',
            constraint=models.UniqueConstraint(fields=('member', 'answer_date'), name='one_daily_answer_per_day'),
        ),
    ]
