# Generated by Django 4.2.19 on 2026-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Pesan singkat yang tampil di banner (maks 280 karakter).', max_length=280, verbose_name='Pesan')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('IMPORTANT', 'Penting'), ('URGENT', 'Darurat')], default='INFO', help_text='Info = hijau (cocok untuk promo), Penting = kuning, Darurat = merah.', max_length=10, verbose_name='Tingkat')),
                ('starts_at', models.DateTimeField(help_text='Banner mulai tampil pada waktu ini (WIB).', verbose_name='Mulai tampil')),
                ('ends_at', models.DateTimeField(help_text='Banner berhenti tampil pada waktu ini (WIB).', verbose_name='Berhenti tampil')),
                ('is_active', models.BooleanField(default=True, help_text='Matikan untuk menyembunyikan tanpa menghapus.', verbose_name='Aktif')),
                ('priority', models.IntegerField(default=0, help_text='Angka lebih besar tampil lebih dulu saat ada beberapa pengumuman.', verbose_name='Prioritas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-priority', '-starts_at'],
            },
        ),
    ]
